sudo: required

language: node_js
node_js: "11"

before_install:
  - source ci_scripts/travis_functions.sh
install:
  - travis_install
script:
  - travis_script
after_success:
  - ls ./electron-chrome/build
  - ls ./electron-chrome/build/dist
  - travis_after_success

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

notifications:
  email: false
