sudo: required

env:
  global:
    - secure: "o1qm2dEuLetpgQaC1hCp84t0R44eUhfJRXcy/CRQunThL8kbtI8LpIqdR8nRk6c/WT6NcLoVi0TPDBYqCHvJ4MQubbIgMdUp11UeB2Z7Cx57Cey8btet4cwCtDgNM8Zt10rTSKr/WR6UDqpRaF7R/k7LhZSA2JMQX2euAsC7aotrjNOoiTzDH/Bok2LvaRHAtfU2v+udftHpzEX7WzVtYJ9k1cqFZFPlo5C/v+9MhOkx1FBOdQ5onmFUIQxz6hfSczl+mUPYcs1T4SrQtEYagoILdLySAuhTFCmPpCHiPwJaLLjLU5nG9otFLXZrrN0kI2cRr+tubW2bC3PG03H4xHP65lHwrLPNcqUX9V1Ic5dZwnMgle9oTOk7n6Sc3JZn21TK+IiHxaK8XUtUxj+hDsiby1kr8sgcGjTp259icXyifY0TmVzaALbg5NVI9rOxq3q9+LjR5070HtaDc3ZSUwO12eSWaSmV3m01VRwvR5sZdPjsZvUOWSpG2S4cto2tU0aBUCiHrS3IlmeoLlH9yTS0jcpviti4jpYqNL7YCXmxHgl6vUo4GJA+NNE1eLJqU9jzEb0ySuEI/jp6/7NQ2IAJySH1OPsux6WG3AX2uSsJ9c15kcvhHgI1NNVwkoHuR1U4CR34VFtayd3bSV0G6r6p0cbV+PUzKI9l4+cvznY="

language: node_js
node_js: "11"

before_install:
  - source ci_scripts/travis_functions.sh
install:
  - travis_install
script:
  - travis_script
after_success:
  - ls ./electron-chrome/build
  - ls ./electron-chrome/build/dist
  - travis_after_success

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

deploy:
  provider: releases
  api_key:
    - secure: "xQdKRV5CYkeWFmU8ncBqL4upzqmyEruk+XoupG56aM0lZtnuxCc5LEUAaEr8nsMzbjkBqp1TYS0ntE67FEE3f6GkVgqaJbkZsFKpfmojtH6byq+7pjhzLdXiLCS2XnY3Q5vABs3JDnAT1p+EiVXquNrbgrm9g9JhvLST1vWGRRnNbp6hOzBDEbozOFUVEBvRCb4o9R56NJ1OfPrexy9VVf+Shw7HcQ+NNgQS9eyERqy4tsSdsjs2i8lRO8LpGsOUL4t2QUgYWvymli566ZUngLcL5jpZ/OLGQ7DNaYzweElKv/FE3wVUFHohV5Uin86THZdA48JaqSNSjIf4qCWIo7H0oWdUrdSFWPl2kLSUwV1dVWHxiSV2dTuGm5uoFPwSjgX2fGa3Kqewfx/iM4TzsHMH6QU0gGphBk0JOu1NeROnvBjLpSPiuXDLlEYOR4QlHHzZZiqLrS0V3vqzGomNoUnGPolaQfXn1csAFyeY8QwN2hBIB34IbrPBZA0WJFCf4B1pS5MNGigWqEuIWGa653Q9N9dj9iioQUnHAJUOc58OWflyQF9dqzK4CxjhsOi0qbOXGYUDEor+NYYSfXDR7wdir1TL+NX4h/TITtLxLjmm7KpkTWXfVmASaumdrfj6kN85cAyAx5Bv66CDWZZ8Ija199rsJfruJbwt1Yd/tbs="
  file:
    - ./electron-chrome/build/dist/Vysor*.AppImage
    - ./electron-chrome/build/dist/Vysor*.snap
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
